### ISSUE TITLE
nodejs index.js

### ISSUE THREAD

**Issue by craigparry** [learn-co-curriculum/js-from-dom-to-node#26]
when I type in nodejs index.js
to execute the index.js file nothing is happening for me. It looks like im in the right lab and the console.log("Hello World!") is in the text editor not in the cosole

**Comment by asabogal** [comment]
save the index.js first, then execute

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @craigparry.

I was unable to replicate your issue, but we have updated this lesson as it was behaving incorrectly.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
