### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by tinyenormous** [learn-co-curriculum/js-from-dom-to-node#32]
hello!
this line 
", breathe in, breath out and realize"
should be 
", breathe in, breath**e** out and realize"

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback, @tinyenormous.

We have fixed this typo and believe your issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
