### ISSUE TITLE
Lesson needs to be updated for latest IDE

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/js-from-dom-to-node#33]
This lesson needs to be updated for IDE 3 and the browser IDE

**Comment by maxwellbenton** [comment]
Thank you, @kwebster2.

We've updated this lesson to make sure it is behaving correctly as a code along and updated the instructions to reference the in browser IDE. I am opening an Known Issue on this lesson as it will need further updating of imagery and specific environment instructions at a later date.
