### ISSUE TITLE
Grammar/clarity issue

### ISSUE THREAD

**Issue by tuzmusic** [learn-co-curriculum/js-from-dom-to-node#34]
The wording of the line "but the goal of every student we serve at The Flatiron School is to teach programmatic thinking as a general way to solve problems." implies that this is the student's goal. I think what you're trying to say is something like "teaching programmatic thinking to every student is the goal of the school". The goal of the student, as such, is to learn (of course).

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @tuzmusic.

We have updated the instructions, changed the wording in this paragraph and believe your issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by tuzmusic** [comment]
Thanks Max. It seems pretty insignificant in retrospect. But it's nice to have my first issue closed! :)
