### ISSUE TITLE
Issue opening the IDE

### ISSUE THREAD

**Issue by pmhofmann** [learn-co-curriculum/js-from-dom-to-node#44]
I do not have the button at the top of the screen to open the IDE, I am only able to open the sandbox

**Comment by asjarzeb** [comment]
I am experiencing the same problem :(

**Comment by austinfrat07** [comment]
Did anyone ever resolve this issue? I am having the same problem.

**Comment by ADuncs13** [comment]
Same problem. Does not seem to be resolved yet.

**Comment by pmhofmann** [comment]
I resolved it by manually forking the lab and cloning it into the IDE, from memory

- click the github button that is on the lab
- that should open the github page for the lab (apologies if the terms aren't 100% accurate
- check to see you have forked the lab in the top right (if the button isn't greyed out do so)
- once that is done click the green button in the top right that says "Clone or Download"
- That opens a little window with some download options, just copy the URL in the window
- Open your IDE from the lab page
- Enter the command:      git clone pastedURL so it looks like "git clone https://github.com/yourusername/lab-name.git"

- Then you are able to complete and submit the lab as normal

**Comment by MedAmineMod** [comment]
Hello @pmhofmann  i have done all the instructions u mentioned,, so i got the project cloned on my LearIDE ,,  
The issue appears when I try to "learn submit"/pushing the changes to the repo  !

**Comment by ehatlebe** [comment]
Thank you @pmhofmann for the helpful instructions. I was able to use them, clone the project, and complete it. Unfortunately, like @MedAmineMod, I am getting stuck when I try to "learn submit". I think the issue might be related to the fact that, when the folder is cloned and opened in the IDE this way, a copy of the js-from-dom-to-node folder and its contents were created and can be used to complete the lab, but this folder is not in the correct location. 

The lab instructions say that the folder order should be: Labs/js-from-dom-to-node/index.js
My folder order is: Development/js-from-dom-to-node-bootcamp-prep-000/index.js

Therefore, index.js cannot be submitted. If there are any additional suggestions on how to fix this, I would be happy to hear them. :)

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @pmhofmann, @asjarzeb, @austinfrat07, @ADuncs13,  and @MedAmineMod,

We apologize for the confusion this lesson has caused. We have updated the lesson so that should now correctly display the Open IDE button and fork the lesson materials automatically.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
