### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vprema94** [learn-co-curriculum/js-from-dom-to-node#48]
I cannot download the files for this lesson. They are not there on the page.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @vprema94.

We have updated this lesson to properly display the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
