### ISSUE TITLE
"Cannot clone this lesson right now"

### ISSUE THREAD

**Issue by thedannysoto** [learn-co-curriculum/js-from-dom-to-node#71]
I'm using the latest version of Chrome and the in-browser IDE. When I try to load the lesson, it gets stuck on the cloning the lesson part.

I used the Ask a question on the sidebar and had a Zoom conversation with technical support and they couldn't figure out how to make it work. Is this a problem on my end? 

I think this is a curriculum issue seeing as though I can't progress in the curriculum until this is resolved.

What can I do to progress in the lessons? Thanks for your help.

<img width="965" alt="Screen Shot 2019-12-07 at 9 39 59 PM" src="https://user-images.githubusercontent.com/58639773/70383834-70d49900-193a-11ea-996a-0063aaca5038.png">

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
