### ISSUE TITLE
Unable to open lesson.

### ISSUE THREAD

**Issue by TylerWool** [learn-co-curriculum/js-from-dom-to-node#74]
I am getting an error message when trying to continue on the flatiron curriculum saying the lesson cannot be opened.
![k](https://user-images.githubusercontent.com/66328753/83555460-4ffd9280-a4dc-11ea-9918-cb9f98e87ec8.PNG)

**Comment by MauryRB** [comment]
Same here. Did you ever find a solution?

**Comment by lizbur10** [comment]
Hello. I'm so sorry to hear this! Unfortunately we are having some IDE problems currently and particularly with this lab. If you are still not able to access it, or if you're consistently having problems with the IDE, please post a question in [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). 

Apologies for the inconvenience!
