### ISSUE TITLE
Cant load lesson

### ISSUE THREAD

**Issue by galennedelchev** [learn-co-curriculum/js-from-dom-to-node#75]
![image](https://user-images.githubusercontent.com/20028188/83917948-a6363400-a76f-11ea-93a9-2042ecb4cc15.png)

The issues i get

**Comment by atencioluke** [comment]
Still seeing this on my end after 2 weeks. Any updates?

**Comment by sickoR** [comment]
Yes it's still the same. Nothing was fixed, hence stopped using it.
________________________________

**Comment by lizbur10** [comment]
Hello. I'm so sorry to hear this! Unfortunately we are having some IDE problems currently and particularly with this lab. If you are still not able to access it, or if you're consistently having problems with the IDE, please post a question in [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). 

Apologies for the inconvenience!
