### ISSUE TITLE
js from dom to node 

### ISSUE THREAD

**Issue by mhwhite22** [learn-co-curriculum/js-from-dom-to-node#77]
Hi there,

The folder with the JS from dom to node lesson on the IDE appears to be empty and I'm getting consistent error messages that looks like:

"// ♥ learn open js-from-dom-to-node-bootcamp-prep-001
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:15:44] ~ "

Tried the FAQs, etc.

**Comment by lizbur10** [comment]
Hello. I'm so sorry to hear this! Unfortunately we are having some IDE problems currently and particularly with this lab. If you are still not able to access it, or if you're consistently having problems with the IDE, please post a question in [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). 

Apologies for the inconvenience!
