### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by dashonterrell** [learn-co-curriculum/js-from-dom-to-node#78]
Good morning, I am using IDE and I continue to get an error when i am typing node index.js into the terminal. I have been trying for days and I have checked the folders and I believe i am in the correct place because i only have 1 folder ( js-from-dom-to-node-bootcamp-prep-001). I am also in the index.js drop folder. 

Thank you

**Comment by lizbur10** [comment]
Hi there,

I'm sorry to hear that you're having this problem! This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
