### ISSUE TITLE
IDE error

### ISSUE THREAD

**Issue by Flakoflash** [learn-co-curriculum/js-from-dom-to-node#82]
The ide is having problems copying the lessons. I cannot do the lab. 
Using browser ide

**Comment by milolynch** [comment]
i'm also having this problem

**Comment by lizbur10** [comment]
Hello. I'm so sorry to hear this! Unfortunately we are having some IDE problems currently and particularly with this lab. If you are still not able to access it, or if you're consistently having problems with the IDE, please post a question in [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson)

Apologies for the inconvenience!
